### ISSUE TITLE
Diverse errors when executing on Mac from terminal. Both python 2 and python 3.

### ISSUE THREAD

**Issue by rrmiraz** [miquelvir/upf-calendar-exporter#1]

**Comment by miquelvir** [comment]
Hi! Can you please post the errors you are getting? I have no way to test the code in Mac directly, so if you post them it will be appreciated.

Anyway, it is Python 3.

**Comment by rrmiraz** [comment]
Hi!

Thank you very much for your quick replay. Later on I’ll send you the terminal error. If you are unable to do the testing, I can help you out. I’m an engineer too ;)

Best,

Raúl Rivas.

Enviado desde mi iPhone

**Comment by miquelvir** [comment]
Hi! Thx for your collaboration, i will wait for the error but i've got a feeling it will be this https://stackoverflow.com/questions/49667195/python-command-os-system-not-working ... Of course collaboration will be appreciated! (and well, i am a potential engineer so let's see if we can solve it)

**Comment by miquelvir** [comment]
@rrmiraz any updates?

**Comment by rrmiraz** [comment]
Hi!

Sorry, I forgot to answer.

It is a problem with the python version included with the Mac operating system. You have to reinstall it as well as all the needed packages. This is required since by default, the system will use it’s own deprecated version despite you have installed any python version on your own.

You could create a tutorial on the readme file explaining how to reinstall (or install) python 3 using homebrew and then all the required packages using pip3.

The code looking good 👍
Nice job!
>

**Comment by miquelvir** [comment]
hi @rrmiraz ! awesome, i'll take note

thx for the update
